
FROM node:18.15.0-alpine

WORKDIR /app

COPY package.json package-lock.json ./

RUN npm install

COPY . .

RUN npm run build

COPY .env build/.env

WORKDIR /app/build

RUN npm ci --production

CMD ["node", "server.js"]

EXPOSE 3333